import {Geist, Geist_Mono} from 'next/font/google';
import './../../globals.css';
import CarRentalHeader from '@/components/inc/car-rental/CarRentalHeader';
import MainHeader from '@/components/inc/MainHeader';
import MainFooter from '@/components/inc/MainFooter';
import CarRentalFooter from '@/components/inc/car-rental/CarRentalFooter';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function CarRentalLayout({children}) {
	return (
		<div>
			<CarRentalHeader />
			{children}
			<CarRentalFooter />
		</div>
	);
}
