import './globals.css';
import MainHeader from '@/components/inc/MainHeader';
import MainFooter from '@/components/inc/MainFooter';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({children}) {
	return (
		<html lang="en">
			<body className="">
				<MainHeader />
				{children}
				<MainFooter />
			</body>
		</html>
	);
}
